### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by frankai** [mythkiven/mkTranslate#4]
Hi! thanks for this useful tool.

Trying to use it the tool (macOS Catalina, strings file) it returns this error, any clue to fix it?

Thanks in advance!
Franky

-----
original:"Miscellaneous Arrows" = "Flechas Varios";
translated:"Miscellaneous Arrows" ="Várias setas";
-----
Traceback (most recent call last):
  File "/usr/local/bin/translate", line 33, in <module>
    main()
  File "/usr/local/bin/translate", line 29, in main
    mkTranslator().translate_doc(filepath=args.file_path, destination=args.dest_language,sourcelanguage=args.sourcelanguage,channel=args.channel)
  File "/Library/Python/2.7/site-packages/mkTranslation/translator.py", line 165, in translate_doc
    self.write_tx(filepath,newFile,r"=\s*\"(.+?)\"\s*;",'="'+'content'+'";',destination,sourcelanguage,channel)
  File "/Library/Python/2.7/site-packages/mkTranslation/translator.py", line 116, in write_tx
    f.write(txd)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 169: ordinal not in range(128)

**Comment by frankai** [comment]
Just in case, I was trying to translate from EN to PT using Google Translate.

**Comment by ProfessorVarox** [comment]
sam issue here

**Comment by ProfessorVarox** [comment]
did you use `pip install mkTranslation` ?
Then use `pip3 install mkTranslation` that worked for me

**Comment by macluky** [comment]
I can confirm that works
note that catelina defaults to pyhton2.7 so be aware which one you pick

**Comment by aydinozkan** [comment]
You may need `sudo -H pip3 install mkTranslation`

**Comment by mythkiven** [comment]
Hi Franky, thanks for reporting!

This is a **Python 2.7 + default ASCII encoding** issue when writing translated output.

### Root cause

From your traceback:
```
File ".../translator.py", line 116, in write_tx
    f.write(txd)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' ...
```

You're on **Python 2.7** (`/Library/Python/2.7/...`). When the translated text contains accented characters like `á` (in `Várias setas`), writing to a file without explicit UTF-8 encoding fails on macOS.

Also, on non-Windows platforms the code opens files without encoding:

```python
f = open(newfile, 'w+')  # no encoding= specified
```

### Fix / workaround

**1. Use Python 3 (recommended):**
```bash
python3 -m pip install --upgrade mkTranslation
python3 $(which translate) -p Localizable.strings -d pt -s en
```

**2. If you must stay on Python 2.7**, set UTF-8 before running:
```bash
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

**3. Ensure your input `.strings` file is UTF-8 encoded** (not UTF-16).

### Long-term

A proper fix in code would be:
```python
open(newfile, 'w+', encoding='utf-8')
```
for both read and write paths on all platforms.

Sorry this bit you on an older Python — upgrading to Python 3 should resolve it immediately. Let me know if you still hit errors after switching.

**Comment by mythkiven** [comment]
Resolved in mkTranslate v2.0 — see comment below.

**Comment by mythkiven** [comment]
Fixed in **v2.0**.

- Python 2 support removed; **Python 3.9+** only.
- All file reads/writes use **UTF-8** explicitly via `io_utils.py`.
- No more ASCII encode errors on accented characters.

Please upgrade: `pip install -U mkTranslation`

Closing as resolved.
