### ISSUE TITLE
请问是不是停止维护了？好像是登录google translate的问题

### ISSUE THREAD

**Issue by william0353** [mythkiven/mkTranslate#7]
Traceback (most recent call last):
  File "translate", line 33, in <module>
  File "translate", line 29, in main
  File "mkTranslation\translator.py", line 163, in translate_doc
  File "mkTranslation\translator.py", line 98, in write_tx
  File "mkTranslation\translator.py", line 72, in translate
  File "mkTranslation\translate_google.py", line 63, in translate
  File "mkTranslation\translate_google.py", line 100, in _translate
  File "mkTranslation\network.py", line 175, in do
  File "mkTranslation\network.py", line 67, in _update
AttributeError: 'NoneType' object has no attribute 'group'
[19168] Failed to execute script translate

**Comment by Rediska47** [comment]
I am getting the same error. Is there any solution?

**Comment by mythkiven** [comment]
你好，抱歉这么久才回复！

项目**没有停更**，但 Google 翻译通道确实经常出问题——你遇到的正是这类情况。

### 错误原因

```
AttributeError: 'NoneType' object has no attribute 'group'
```

出在 `network.py` 获取 Google `tkk` token 时：

```python
raw_tkk = self.RE_TKK.search(r.text)
# ...
code = unicode(self.RE_TKK.search(r.text).group(1))  # r.text 里已找不到 tkk
```

**原因：** Google 网页结构变了，正则抓不到 `tkk` token。这是所有「爬 Google 翻译网页」方案的共同问题，不是你是否「登录」Google 的问题——**本工具不需要 Google 账号登录**。

### 解决办法

**1. 改用有道（国内推荐）：**
```bash
translate -p 你的文件.strings -d en -c youdao -s zh
```

**2. 升级版本：**
```bash
pip install --upgrade mkTranslation
```

**3. 确认网络：**
```bash
ping youdao.com -c 3
```

**4. 如需 Google 通道** — 需要能稳定访问 `translate.google.com`（通常要代理）。

### 关于维护状态

- 简繁互译（`-d s` / `-d t`）**不依赖外部 API**，一直可用
- Google / 有道依赖第三方网页接口，接口一变就要修
- 长期更稳的方案是接入 [Google Cloud Translation API](https://cloud.google.com/translate)（付费官方接口）

如果你愿意，可以贴一下：Windows 版本、`pip show mkTranslation` 版本号、用的完整命令，我帮你确认该走哪个通道。

**Comment by mythkiven** [comment]
Resolved in mkTranslate v2.0 — see comment below.

**Comment by mythkiven** [comment]
Fixed in **v2.0**. Project is actively maintained.

- Google channel rebuilt with **`deep-translator`** (no more broken `tkk` scraping).
- Optional official API via `GOOGLE_TRANSLATE_API_KEY`.
- Default channel changed to **Youdao** for reliability.
- Auto fallback between channels.

No Google account login is required. Please upgrade:

```bash
pip install -U mkTranslation
```

Closing as resolved.
