### ISSUE TITLE
Various error with Localizable.strings

### ISSUE THREAD

**Issue by JulesMoorhouse** [mythkiven/mkTranslate#8]
Hi,

I'm getting the following errors... I'd be grateful for some advice.

I've tried...

```
translate -p Localizable.strings -d 'de'
translate -p ./Localizable.strings -d 'de'
translate -p ./Localizable.strings -d 'de' -s 'en'
```

Here's the errors...

```
translate -p Localizable.strings -d 'de'
Target language: de
[Use google translation]
translating..
Traceback (most recent call last):
  File "/usr/local/bin/translate", line 33, in <module>
    main()
  File "/usr/local/bin/translate", line 29, in main
    mkTranslator().translate_doc(filepath=args.file_path, destination=args.dest_language,sourcelanguage=args.sourcelanguage,channel=args.channel)
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/translator.py", line 165, in translate_doc
    self.write_tx(filepath,newFile,r"=\s*\"(.+?)\"\s*;",'="'+'content'+'";',destination,sourcelanguage,channel)
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/translator.py", line 90, in write_tx
    line = f.readline()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

```
pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

Thanks...

**Comment by trapper-** [comment]
Same errors for me

**Comment by trapper-** [comment]
I made some progress on this error, the Localizable.strings file that Xcode generates is in UTF-16 with BOM format for some strange reason, causes the invalid start byte error. Resaved it as UTF-8 and got past that error, but ran into another :(

```
translate -p ./Localizable.strings -d es
Target language: es
[Use google translation]
translating..
original:/* No comment provided by engineer. */
skip: /* No comment provided by engineer. */
translated:/* No comment provided by engineer. */
-----
original:"%@ already exists." = "%@ already exists.";
Traceback (most recent call last):
  File "/usr/local/bin/translate", line 33, in <module>
    main()
  File "/usr/local/bin/translate", line 29, in main
    mkTranslator().translate_doc(filepath=args.file_path, destination=args.dest_language,sourcelanguage=args.sourcelanguage,channel=args.channel)
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/translator.py", line 165, in translate_doc
    self.write_tx(filepath,newFile,r"=\s*\"(.+?)\"\s*;",'="'+'content'+'";',destination,sourcelanguage,channel)
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/translator.py", line 101, in write_tx
    txc = self.translate(line[0],des,lan,channel)
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/translator.py", line 73, in translate
    return mkGoogleTranslator().translate(word, dest=destination).text
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/translate_google.py", line 63, in translate
    data = self._translate(text, dest, src)
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/translate_google.py", line 100, in _translate
    token = self.token_acquirer.do(text)
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/network.py", line 175, in do
    self._update()
  File "/usr/local/lib/python3.9/site-packages/mkTranslation/network.py", line 67, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by JulesMoorhouse** [comment]
Ahhh right...

I get the same error 🙁

@mythkiven can you help please ?

Merry Christmas

**Comment by Rediska47** [comment]
I am getting the same error. Is there any solution?
```
translate -p Localizable.strings -d 'ru'
original:"ACCEPT_LARGE_VIDEO_DOWNLOAD"="Download";
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/translate", line 33, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/translate", line 29, in main
    mkTranslator().translate_doc(filepath=args.file_path, destination=args.dest_language,sourcelanguage=args.sourcelanguage,channel=args.channel)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mkTranslation/translator.py", line 165, in translate_doc
    self.write_tx(filepath,newFile,r"=\s*\"(.+?)\"\s*;",'="'+'content'+'";',destination,sourcelanguage,channel)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mkTranslation/translator.py", line 101, in write_tx
    txc = self.translate(line[0],des,lan,channel)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mkTranslation/translator.py", line 73, in translate
    return mkGoogleTranslator().translate(word, dest=destination).text
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mkTranslation/translate_google.py", line 63, in translate
    data = self._translate(text, dest, src)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mkTranslation/translate_google.py", line 100, in _translate
    token = self.token_acquirer.do(text)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mkTranslation/network.py", line 175, in do
    self._update()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mkTranslation/network.py", line 67, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by mythkiven** [comment]
Hi Jules, thanks for the detailed error report!

### Root cause

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0
```

Byte `0xFF` at position 0 almost always means your `Localizable.strings` file is **UTF-16 LE with BOM** (common when edited/saved by some macOS tools or Xcode versions), **not UTF-8**.

mkTranslate on macOS opens files with default encoding (UTF-8):

```python
f = open(oldfile)  # expects UTF-8
```

### Fix

**1. Convert the file to UTF-8 first:**

```bash
# Check encoding
file Localizable.strings

# Convert UTF-16 → UTF-8 (macOS)
iconv -f UTF-16 -t UTF-8 Localizable.strings > Localizable_utf8.strings
translate -p Localizable_utf8.strings -d de -s en
```

**In Xcode:** re-save the file as UTF-8 (File Inspector → Text Encoding → UTF-8).

**2. Use Python 3:**
```bash
python3 -m pip install --upgrade mkTranslation
translate -p ./Localizable.strings -d de -s en
```

**3. Your commands look correct** — the path and `-s en` are fine. The encoding is the blocker.

### Optional code improvement

A more robust approach would be auto-detecting BOM:

```python
import codecs
# try utf-8, fallback utf-16
```

For now, converting to UTF-8 before running should unblock you.

Let me know if conversion works or if you get a different error!

**Comment by mythkiven** [comment]
Resolved in mkTranslate v2.0 — see comment below.

**Comment by mythkiven** [comment]
Fixed in **v2.0**.

`0xff` at position 0 = **UTF-16 BOM** file. v2.0 auto-detects encoding:

- UTF-8 / UTF-8-sig / UTF-16

No manual `iconv` conversion needed. Upgrade and retry:

```bash
pip install -U mkTranslation
translate -p ./Localizable.strings -d de -s en -c youdao
```

Closing as resolved.
