### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TheMandalorianHub** [mythkiven/mkTranslate#9]
original:    <string name="资料页邀请"><![CDATA[Invitation<font color="#999999">(optional)</font>]]></string>
使用有道备用翻译通道2
使用接口，仅支持中英互译,将翻译为英文
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translate_youdao.py", line 48, in trans1
    if(resp.json()['translation']):
KeyError: 'translation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translate_youdao.py", line 76, in trans2
    return resp.json()['translateResult'][0][0]['tgt']
KeyError: 'translateResult'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/translate", line 33, in <module>
    main()
  File "/opt/homebrew/bin/translate", line 29, in main
    mkTranslator().translate_doc(filepath=args.file_path, destination=args.dest_language,sourcelanguage=args.sourcelanguage,channel=args.channel)
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translator.py", line 168, in translate_doc
    self.write_tx(filepath,newFile,r">\s*(.+?)\s*</string>",'>'+'content'+'</string>',destination,sourcelanguage,channel)
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translator.py", line 101, in write_tx
    txc = self.translate(line[0],des,lan,channel)
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translator.py", line 75, in translate
    return mkYouDaoTranslator().translate(word,destination,language)
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translate_youdao.py", line 37, in translate
    return self.trans1(text,dest,src)
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translate_youdao.py", line 52, in trans1
    return self.trans2(text,dest,src)
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translate_youdao.py", line 78, in trans2
    return self.trans3(text,dest,src)
  File "/opt/homebrew/lib/python3.9/site-packages/mkTranslation/translate_youdao.py", line 94, in trans3
    return self.result['translation'][0]
KeyError: 'translation'

**Comment by mythkiven** [comment]
Hi Mondo, thanks for the full traceback!

### What's happening

Your string contains **HTML + CDATA**:

```xml
<string name="资料页邀请"><![CDATA[Invitation<font color="#999999">(optional)</font>]]></string>
```

Two problems stacked:

**1. Regex can't extract CDATA content properly**

mkTranslate matches:
```python
r">\s*(.+?)\s*</string>"
```
CDATA blocks and nested `<font>` tags often cause **skip** or partial/wrong matches.

**2. Youdao fallback only supports zh ↔ en**

Log shows:
```
使用接口，仅支持中英互译,将翻译为英文
KeyError: 'translation'
```

When Youdao's primary APIs fail, `trans3` uses a legacy free endpoint that **only handles Chinese ↔ English**. Your string is mixed Chinese key + English HTML — all three Youdao channels failed.

### Workarounds

**1. Pre-process: extract plain text before translating**

Translate only the human-readable part:
```
Invitation (optional)
```
Then manually wrap back into XML.

**2. Try Google channel** (if you have access):
```bash
translate -p strings.xml -d en -c google -s zh
```

**3. Simplify the string format** for batch translation:

Instead of CDATA+HTML inline, use:
```xml
<string name="invite_title">Invitation</string>
<string name="invite_optional">(optional)</string>
```

**4. For complex HTML strings** — batch auto-translation may not be the right tool; translate plain strings and keep markup in code.

### Why all three Youdao channels failed

Youdao periodically changes/limits their web API. The `sign` algorithm in `translate_youdao.py` can break without warning — same class of issue as Google token scraping.

Sorry this hit a nasty edge case. If you can share a **minimal repro file** (2-3 strings), I can suggest exact preprocessing steps.

**Comment by mythkiven** [comment]
Resolved in mkTranslate v2.0 — see comment below.

**Comment by mythkiven** [comment]
Fixed in **v2.0**.

Improvements for CDATA / HTML strings:
- **ElementTree** XML parser (no more fragile regex)
- **Channel auto-fallback** (Youdao ↔ Google)
- Better error messages when translation fails

For very complex HTML-in-string content, we still recommend splitting into plain-text strings for batch translation.

Upgrade: `pip install -U mkTranslation`

Closing as resolved.
